/** MONGODB SCHEMA TYPE **/
const SCHEMA_TYPE = {
    TIMESHEET: "timesheets",
    HISTORY: "history",
    USERID: "userId",
    MILESTONE: "milestone",
    USERS: "users",
    ADMIN_DETAIL: "adminDetail",
    WASABICREDENTIALS: "wasabicredentials",
    PROJECT_MAIN_TEMPLATES: "ProjectTemplate",
    TIMETRACKER_DOWNLOAD: "timeTrackerDownload",
    COMPANIES: "companies",
    PROJECT_TEMPLATES: "project_templates",
    PROJECT_TAB_COMPONENTS: "project_tab_components",
    PROJECT_STATUS_TEMPLATES: "project_status_template",
    TASK_TYPE_TEMPLATES: "task_type_templates",
    TASK_STATUS_TEMPLATES: "task_status_templates",
    TEAMS_MANAGEMENT: "teams_management",
    COMPANY_USERS: "company_users",
    RULES: "rules",
    ESTIMATES_TIME: "estimated_time",
    CURRENCY_LIST: "currency_list",
    PROJECTS: "projects",
    SETTINGS: "settings",
    APPS: "apps",
    NOTIFICATIONS: "notifications",
    NOTIFICATIONS_SETTINGS: "notifications_settings",
    MENTIONS: "mentions",
    TASKS: "tasks",
    COMMON:"common",
    MAIN_CHATS: "main_chats",
    GOLBAL : "global",
    COMMENTS: "comments",
    PROJECT_RULES:"projectRules",
    SUBSCRIPTIONPLAN: "subscriptionPlan",
    PLANFEATURE: "planFeature",
    PLANFEATUREDISPLAY: "planFeatureDisplay",
    SUBSCRIPTIONS: 'subscriptions',
    INVOICES: 'invoices',
    CREDITNOTES: 'creditNotes',
    PRECOMPANIES: 'preCompanies',
    CUSTOM_FIELDS: "customField",
    SPRINTS:"sprints",
    FOLDERS: "folders",
    RESTRICTED_EXTENSIONS: "restrictedExtensions",
    GLOBAL_CUSTOM_FIELDS: "global_custom_fields",
    TOURS: "tours",
    BUCKETS: "buckets",
    GLOBALFILTER:'global_filter',
    HOURLY_MILESTONE_WEEKLY_RANGE:'hourly_milestone_weekly_range',
    USER_AUTH: "userAuth",
    RESET_ATTEMPT: "resetAttempt",
    SESSIONS: "sessions",
    USERDASHBOARD:'userDashboard',
    REFERCODE: "refferalcodes",
    REFFERALMAPPING: "refferalmapping",
    GLOBALSETTING: "globalSetting",
    WEBHOOKS: "webhooks",
    WEBHOOK_LOGS: "webhookLogs",
    RECENTVISITS: "recentVisits",
    API_TOKENS: "apiTokens",
    API_ACTIVITY_LOGS: "apiActivityLogs",
    EXPORT_JOBS: "exportJobs",
    IMPORT_JOBS: "importJobs",
    EPICS: "epics",
    PAGES: "pages",
    PAGE_VERSIONS: "pageVersions",
    PUBLIC_SHARES: "publicShares",
    INTAKE_ITEMS: "intakeItems",
    PUBLIC_SHARE_INDEX: "publicShareIndex",
    RECURRING_TASKS: "recurring_tasks",
    REMINDERS: "reminders",
    NOTES: "notes",
    GENERAL_REMINDERS: "general_reminders",
    GENERAL_REMINDER_QUEUE: "general_reminder_queue",
    CLIPS: "clips",
    TIMESHEET_APPROVAL: "timesheet_approval",
    BILLING_RATES: "billing_rates",
    SSO_CONFIGS: "sso_configs",
    AUDIT_LOGS: "audit_logs",
    SCIM_CONFIGS: "scim_configs",
    PTO_ENTRIES: "pto_entries",
    PORTFOLIOS: "portfolios",
    SAVED_REPORTS: "saved_reports",
    REPORT_SCHEDULES: "report_schedules",
    EMAIL_INBOXES: "email_inboxes",
    CALENDAR_FEEDS: "calendar_feeds",
    AUTOMATION_RULES: "automation_rules",
    INTEGRATION_CONNECTIONS: "integration_connections",
    CLOUD_STORAGE_CONNECTIONS: "cloud_storage_connections",
}

module.exports = {
    SCHEMA_TYPE
};